name: 'Compare two semver versions'
description: 'Compares two semver versions and outputs the result'

outputs:
  latestTag: # id of output
    description: 'The latest tag version'
runs:
  using: 'node16'
  main: 'index.js'
