# Workflow for Testing Actions

# Workflow for ESLint
name: 🧪 Testing Actions

on: push
  branches:  
    - 'actions-test'   # excludes actions-test branch

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  testing:
    runs-on: ubuntu-latest
      steps:
      - run: echo "Testing Github Actions on branch $GITHUB_REF"