# Workflow for Testing Actions
name: 🧪 Testing Actions

on:
  push:
    branches:
      - 'actions-test' # only run on actions-test branch

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing Github Actions on branch $GITHUB_REF"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'

      - run: echo "Previous tag is ${{ steps.previoustag.outputs.tag }}
