version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      time: '04:00'
      timezone: Pacific/Auckland
    open-pull-requests-limit: 10
    labels:
      - javascript
      - dependencies
      - bot-pr
    reviewers:
      - sharesight/frontend

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: '04:00'
      timezone: Pacific/Auckland
    labels:
      - dependencies
      - bot-pr
      - gh-actions
    reviewers:
      - sharesight/dev-ops
