# Workflow for Jest Suite
name: 🃏 Jest

on: push

jobs:
  jest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: 'Setup Node, Caching, and Yarn install'
        uses: ./.github/actions/node-yarn

      - name: Run jest
        run: yarn test:ci

  Slack Notification:
    needs: jest
    uses: rtCamp/action-slack-notify@v2
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_CHANNEL: github-actions
      SLACK_TITLE: 'Jest Suite'
      SLACK_USERNAME: 'Demo-App-Jest'
      SLACK_COLOR: ${{ job.status }}
      SLACK_MESSAGE: 'Jest Suite has completed'
      SLACK_FOOTER: ''
      SLACK_ICON_EMOJI: ':jest:'
