# Workflow for Jest Suite
name: 🃏 Jest

on:
  push:
    branches:
      - '**' # matches every branch
      - '!actions-test' # excludes actions-test branch

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  jest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: 'Setup Node, Caching, and Yarn install'
        uses: ./.github/actions/node-yarn

      - name: Run jest
        run: yarn test:ci

  slack:
    needs: jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: 'Jest Suite'
          SLACK_USERNAME: ${{ github.event.repository.name }}-Jest
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Jest Suite has completed'
          SLACK_FOOTER: ''
          SLACK_ICON_EMOJI: ':jest'
